accounts:
  upper_limit: 0 # cents, 0 = disabled, but only here
  lower_limit: -2000
sounds:
  failed:
    - /home/ole/github/rest/strichliste-rs/public/sounds/wobble.wav
  generic:
    - /home/ole/github/rest/strichliste-rs/public/sounds/kaching.wav
  articles:
    Spezi:
      - /home/ole/github/rest/strichliste-rs/public/sounds/spezi_1.wav
