---
name: "Build"
on:  # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Fetch Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build package
        run: |
          nix build
      - name: Show log if build failed
        if: failure()
        run: |
          nix log
        
