---
name: "Check"
on: # yamllint disable-line rule:truthy
  check_suite:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check:
    runs-on: self-hosted
    steps:
      - name: Fetch Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check package
        run: |
          nix flake check
      - name: Generate format diff
        if: failure()
        run: |
          nix fmt
          git diff --exit-code > patch.diff
      - name: Upload format patch diff
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: format-patch-diff
          path: patch.diff
